### ISSUE TITLE
Prettier options?

### ISSUE THREAD

**Issue by slacktracer** [kentcdodds/prettier-eslint-atom#16] opened 2017-01-28 22:01 UTC
I can not find a way to set the prettier options. Specifically the max line length. I am not sure what I am missing. I was expecting the prettier options would be available on the package settings...

Is it not a feature yet or am I just being silly here? =P

**Comment by kentcdodds** [comment] 2017-01-28 22:09
Maybe we could be more explicit, but everything is based off of your eslint config. That happens [here](https://github.com/kentcdodds/prettier-eslint/blob/master/src/utils.js#L8). There are plans (see #12) to configure a few things that you normally couldn't configure with eslint (like the flow parser). But other than that, we shouldn't need to allow this.

That said, would you like to [make a pull request](http://makeapullrequest.com/) to add something to explain this in the README?

**Comment by slacktracer** [comment] 2017-01-29 10:24
@kentcdodds 

Absolutely! =)

I see now. I imagined something like that was happening under the hood.

I was just doing something wrong on my end...

I'll get back to you. Thank you!

**Comment by slacktracer** [comment] 2017-01-29 12:16
@kentcdodds 

That's what is confusing me:

[The code using just Prettier.](https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20about%20%3D%20%7B%5Cn%20%20equal%3A%20%7B%20hit%3A%20true%2C%20name%3A%20'equal'%2C%20symbol%3A%20'%3C-------%3C%5C%5Cn%3C-------%3C'%20%7D%2C%5Cn%20%20cover%3A%20%7B%20hit%3A%20true%2C%20name%3A%20'cover'%2C%20symbol%3A%20'%3C---------%3C%5C%5Cn%20%3C-------%3C%20'%20%7D%2C%5Cn%20%20coverLeft%3A%20%7B%20hit%3A%20true%2C%20name%3A%20'coverLeft'%2C%20symbol%3A%20'%3C---------%3C%5C%5Cn%3C--------%3C%20'%20%7D%2C%5Cn%20%20coverRight%3A%20%7B%5Cn%20%20%20%20hit%3A%20true%2C%5Cn%20%20%20%20name%3A%20'coverRight'%2C%5Cn%20%20%20%20symbol%3A%20'%3C---------%3C%5C%5Cn%20%3C--------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20inside%3A%20%7B%20hit%3A%20true%2C%20name%3A%20'inside'%2C%20symbol%3A%20'%20%3C-------%3C%20%5C%5Cn%3C---------%3C'%20%7D%2C%5Cn%20%20insideLeft%3A%20%7B%5Cn%20%20%20%20hit%3A%20true%2C%5Cn%20%20%20%20name%3A%20'insideLeft'%2C%5Cn%20%20%20%20symbol%3A%20'%3C--------%3C%20%5C%5Cn%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20insideRight%3A%20%7B%5Cn%20%20%20%20hit%3A%20true%2C%5Cn%20%20%20%20name%3A%20'insideRight'%2C%5Cn%20%20%20%20symbol%3A%20'%20%3C--------%3C%5C%5Cn%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20overlapLeft%3A%20%7B%5Cn%20%20%20%20hit%3A%20true%2C%5Cn%20%20%20%20name%3A%20'overlapLeft'%2C%5Cn%20%20%20%20symbol%3A%20'%3C---------%3C%5C%5Cn%20%20%20%20%20%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20overlapRight%3A%20%7B%5Cn%20%20%20%20hit%3A%20true%2C%5Cn%20%20%20%20name%3A%20'overlapRight'%2C%5Cn%20%20%20%20symbol%3A%20'%20%20%20%20%20%3C---------%3C%5C%5Cn%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20outsideLeft%3A%20%7B%5Cn%20%20%20%20hit%3A%20false%2C%5Cn%20%20%20%20name%3A%20'outsideLeft'%2C%5Cn%20%20%20%20symbol%3A%20'%3C---------%3C%5C%5Cn%20%20%20%20%20%20%20%20%20%20%20%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%20%20outsideRight%3A%20%7B%5Cn%20%20%20%20hit%3A%20false%2C%5Cn%20%20%20%20name%3A%20'outsideRight'%2C%5Cn%20%20%20%20symbol%3A%20'%20%20%20%20%20%20%20%20%20%20%20%3C---------%3C%5C%5Cn%3C---------%3C'%2C%5Cn%20%20%7D%2C%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

Prettier makes the line length correct. 80.

But on Atom the 4th line goes beyond the limit. ESLint correctly tells me so. And it's not fixed no matter how many times I save.

```
const about = {
  equal: { hit: true, name: 'equal', symbol: '<-------<\n<-------<' },
  cover: { hit: true, name: 'cover', symbol: '<---------<\n <-------< ' },
  coverLeft: { hit: true, name: 'coverLeft', symbol: '<---------<\n<--------< ' },
  coverRight: {
    hit: true,
    name: 'coverRight',
    symbol: '<---------<\n <--------<',
  },
  inside: { hit: true, name: 'inside', symbol: ' <-------< \n<---------<' },
  insideLeft: {
    hit: true,
    name: 'insideLeft',
    symbol: '<--------< \n<---------<',
  },
  insideRight: {
    hit: true,
    name: 'insideRight',
    symbol: ' <--------<\n<---------<',
  },
  overlapLeft: {
    hit: true,
    name: 'overlapLeft',
    symbol: '<---------<\n     <---------<',
  },
  overlapRight: {
    hit: true,
    name: 'overlapRight',
    symbol: '     <---------<\n<---------<',
  },
  outsideLeft: {
    hit: false,
    name: 'outsideLeft',
    symbol: '<---------<\n           <---------<',
  },
  outsideRight: {
    hit: false,
    name: 'outsideRight',
    symbol: '           <---------<\n<---------<',
  },
}
```

What gives...? 

---
My eslintrc.js:

```
module.exports = {
  env: { es6: true, node: true },
  extends: 'eslint:recommended',
  // extends: 'airbnb-base',
  rules: {
    'array-bracket-spacing': [ 'error', 'always' ],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always',
        exports: 'always',
        functions: 'never',
      },
    ],
    'max-len': [ 'error', 80 ],
    'object-curly-spacing': [ 'error', 'always' ],
    semi: [ 'error', 'never' ],
  },
}
```

**Comment by kentcdodds** [comment] 2017-01-29 15:00
Could you update to the latest version? This may be a prettier bug that was fixed.

**Comment by slacktracer** [comment] 2017-01-29 15:12
I am on 1.2.5. I think I updated yesterday, or the day before. Isn't it latest?

Atom says all packages are up to date...

Did you could/tried to reproduce it? I mean, it does not happen on your set up?

**Comment by kentcdodds** [comment] 2017-01-29 15:48
Hmmm... this appears to be an off-by-one error. For example, here's the minimal amount of code needed to produce the bug:

```javascript
const about = {
  coverLeft: { hit: true, name: 'coverLeft', symbol: '<---------<\n<--------< ' },
};
```

If we format that, nothing happens and we get a linting error.

But let's add a space in the string `symbol`:

```javascript
const about = {
  coverLeft: { hit: true, name: 'coverLeft', symbol: ' <---------<\n<--------< ' },
};
```

And that formats like so:

```javascript
const about = {
  coverLeft: {
    hit: true,
    name: 'coverLeft',
    symbol: ' <---------<\n<--------< ',
  },
};
```

So, I'm not sure where the problem is honestly. If I pull up devtools in Atom, and I log what prettier formats things like, it's not changing the original code at all. So it appears to me to be a prettier bug.

I'm afraid I don't have any more time to look into this. If you could dig further that would be great. Thanks!

**Comment by slacktracer** [comment] 2017-01-29 19:08
I understand. It interesting how online prettier formats correctly.

I'll look into it.

Thank you. Thank you very much!

**Comment by kentcdodds** [comment] 2017-01-29 19:32
Let's leave this open. This is definitely a bug somewhere and I don't want to forget about it. Thanks for looking into it!

**Comment by slacktracer** [comment] 2017-01-29 20:21
Sure, sorry. Thanks again.

**Comment by kentcdodds** [comment] 2017-03-05 17:56
This package has been deprecated. Please see the README for instructions on moving to the new plugin.

**Closed as completed by kentcdodds** 2017-03-05 17:56 UTC
Labels: help wanted
